import type { SeedProduct } from './types.js'

/**
 * Demo catalog: residential and commercial air conditioners, spare parts and installation
 * accessories, sold from stock or "bajo pedido". Prices in USD. No photos (they are uploaded
 * from the admin panel).
 */
export const products: SeedProduct[] = [
    {
        id: 'ac-daikin-ftkf09',
        slug: 'split-daikin-inverter-9000-btu',
        name: 'Split Daikin Inverter 9.000 BTU',
        category: 'aires-residenciales',
        brand: 'Daikin',
        model: 'FTKF09',
        sku: 'DK-FTKF09-220',
        price: 520,
        stockMode: 'STOCK',
        stock: 6,
        leadTimeDays: null,
        btu: 9000,
        voltage: '220V',
        isInverter: true,
        refrigerant: 'R32',
        description:
            'Equipo split de pared con tecnología inverter, ideal para habitaciones de hasta 12 m². Funcionamiento silencioso y bajo consumo gracias a su compresor de velocidad variable.',
        highlights: [
            'Ahorro de energía de hasta 40 %',
            'Modo silencioso de 21 dB',
            'Refrigerante ecológico R32',
            'Filtro purificador de aire',
        ],
        specs: [
            { label: 'Capacidad', value: '9.000 BTU' },
            { label: 'Tecnología', value: 'Inverter' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R32' },
            { label: 'Eficiencia (SEER)', value: '18' },
            { label: 'Área recomendada', value: 'Hasta 12 m²' },
            { label: 'Garantía', value: '1 año en el equipo, 5 años en el compresor' },
        ],
        variants: [],
        tags: ['nuevo'],
        createdAt: '2026-08-20T13:00:00.000Z',
    },
    {
        id: 'ac-lg-dual-12',
        slug: 'split-lg-dual-inverter-12000-btu',
        name: 'Split LG Dual Inverter 12.000 BTU',
        category: 'aires-residenciales',
        brand: 'LG',
        model: 'S4-Q12JA3WF',
        sku: 'LG-S4Q12-220',
        price: 640,
        compareAtPrice: 690,
        stockMode: 'STOCK',
        stock: 8,
        leadTimeDays: null,
        btu: 12000,
        voltage: '220V',
        isInverter: true,
        refrigerant: 'R32',
        description:
            'El equipo más vendido para habitaciones y oficinas medianas. Compresor Dual Inverter de LG, enfriamiento rápido y control desde el celular con ThinQ.',
        highlights: [
            'Compresor Dual Inverter con 10 años de garantía',
            'Enfriamiento rápido Jet Cool',
            'Control por Wi-Fi con LG ThinQ',
            'Protección contra variaciones de voltaje',
        ],
        specs: [
            { label: 'Capacidad', value: '12.000 BTU' },
            { label: 'Tecnología', value: 'Dual Inverter' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R32' },
            { label: 'Eficiencia (SEER)', value: '20' },
            { label: 'Área recomendada', value: '12 a 18 m²' },
            { label: 'Conectividad', value: 'Wi-Fi (LG ThinQ)' },
            { label: 'Garantía', value: '1 año en el equipo, 10 años en el compresor' },
        ],
        variants: [],
        tags: ['bestseller', 'oferta'],
        createdAt: '2026-06-02T13:00:00.000Z',
    },
    {
        id: 'ac-gree-lomo-12',
        slug: 'split-gree-lomo-12000-btu',
        name: 'Split Gree Lomo 12.000 BTU',
        category: 'aires-residenciales',
        brand: 'Gree',
        model: 'GWC12QC',
        sku: 'GR-GWC12-220',
        price: 480,
        stockMode: 'STOCK',
        stock: 10,
        leadTimeDays: null,
        btu: 12000,
        voltage: '220V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Split convencional confiable y económico, con la calidad de Gree. Una opción práctica para habitaciones de uso moderado.',
        highlights: [
            'Excelente relación precio-capacidad',
            'Función de autodiagnóstico',
            'Modo sueño y temporizador de 24 horas',
        ],
        specs: [
            { label: 'Capacidad', value: '12.000 BTU' },
            { label: 'Tecnología', value: 'Convencional (on/off)' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: '12 a 16 m²' },
            { label: 'Garantía', value: '1 año en el equipo, 3 años en el compresor' },
        ],
        variants: [],
        tags: ['bestseller'],
        createdAt: '2026-04-10T13:00:00.000Z',
    },
    {
        id: 'ac-gree-pular-9',
        slug: 'split-gree-pular-9000-btu-110v',
        name: 'Split Gree Pular 9.000 BTU 110V',
        category: 'aires-residenciales',
        brand: 'Gree',
        model: 'GWC09PB',
        sku: 'GR-GWC09-110',
        price: 410,
        stockMode: 'STOCK',
        stock: 0,
        leadTimeDays: null,
        btu: 9000,
        voltage: '110V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Split de 9.000 BTU a 110V, pensado para espacios sin toma de 220V. Instalación sencilla y operación estable.',
        highlights: [
            'Funciona con toma de 110V',
            'Panel con pantalla LED oculta',
            'Arranque suave para proteger el compresor',
        ],
        specs: [
            { label: 'Capacidad', value: '9.000 BTU' },
            { label: 'Tecnología', value: 'Convencional (on/off)' },
            { label: 'Voltaje', value: '110V / 60 Hz' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: 'Hasta 12 m²' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-03-15T13:00:00.000Z',
    },
    {
        id: 'ac-midea-xtreme-18',
        slug: 'split-midea-xtreme-save-inverter-18000-btu',
        name: 'Split Midea Xtreme Save Inverter 18.000 BTU',
        category: 'aires-residenciales',
        brand: 'Midea',
        model: 'MSAGBU-18HRFN8',
        sku: 'MD-XS18-220',
        price: 890,
        stockMode: 'STOCK',
        stock: 4,
        leadTimeDays: null,
        btu: 18000,
        voltage: '220V',
        isInverter: true,
        refrigerant: 'R32',
        description:
            'Inverter de alta eficiencia para salas y oficinas amplias. Mantiene la temperatura estable con un consumo muy bajo.',
        highlights: [
            'Eficiencia clase A',
            'Autolimpieza del evaporador',
            'Control por Wi-Fi opcional',
            'Funcionamiento con voltaje desde 150V',
        ],
        specs: [
            { label: 'Capacidad', value: '18.000 BTU' },
            { label: 'Tecnología', value: 'Inverter' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R32' },
            { label: 'Eficiencia (SEER)', value: '19' },
            { label: 'Área recomendada', value: '20 a 28 m²' },
        ],
        variants: [],
        tags: ['nuevo'],
        createdAt: '2026-09-01T13:00:00.000Z',
    },
    {
        id: 'ac-midea-mission-24',
        slug: 'split-midea-mission-24000-btu',
        name: 'Split Midea Mission 24.000 BTU',
        category: 'aires-residenciales',
        brand: 'Midea',
        model: 'MSMBC-24CRN1',
        sku: 'MD-MS24-220',
        price: 980,
        stockMode: 'STOCK',
        stock: 3,
        leadTimeDays: null,
        btu: 24000,
        voltage: '220V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Split convencional de gran capacidad para salas, comedores y oficinas de planta abierta.',
        highlights: [
            'Flujo de aire de largo alcance',
            'Filtro de alta densidad lavable',
            'Reinicio automático tras un corte de luz',
        ],
        specs: [
            { label: 'Capacidad', value: '24.000 BTU' },
            { label: 'Tecnología', value: 'Convencional (on/off)' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: '30 a 40 m²' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-02-12T13:00:00.000Z',
    },
    {
        id: 'ac-samsung-windfree-24',
        slug: 'split-samsung-windfree-inverter-24000-btu',
        name: 'Split Samsung WindFree Inverter 24.000 BTU',
        category: 'aires-residenciales',
        brand: 'Samsung',
        model: 'AR24TSFABWK',
        sku: 'SS-WF24-220',
        price: 1390,
        stockMode: 'ON_ORDER',
        stock: 0,
        leadTimeDays: 20,
        btu: 24000,
        voltage: '220V',
        isInverter: true,
        refrigerant: 'R32',
        description:
            'Enfriamiento sin corrientes de aire directas gracias a sus 23.000 microorificios. Máximo confort y ahorro para espacios amplios. Disponible bajo pedido.',
        highlights: [
            'Tecnología WindFree sin corrientes directas',
            'Compresor Digital Inverter con 10 años de garantía',
            'Control por Wi-Fi con SmartThings',
            'Filtro de partículas finas',
        ],
        specs: [
            { label: 'Capacidad', value: '24.000 BTU' },
            { label: 'Tecnología', value: 'Digital Inverter' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R32' },
            { label: 'Eficiencia (SEER)', value: '21' },
            { label: 'Área recomendada', value: '30 a 40 m²' },
            { label: 'Tiempo de entrega', value: '20 días aprox.' },
        ],
        variants: [],
        tags: ['nuevo'],
        createdAt: '2026-09-10T13:00:00.000Z',
    },
    {
        id: 'ac-gree-pt-36',
        slug: 'piso-techo-gree-36000-btu',
        name: 'Piso-techo Gree 36.000 BTU',
        category: 'aires-comerciales',
        brand: 'Gree',
        model: 'GTH36K3FI',
        sku: 'GR-PT36-220',
        price: 1950,
        stockMode: 'ON_ORDER',
        stock: 0,
        leadTimeDays: 30,
        btu: 36000,
        voltage: '220V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Equipo piso-techo para locales comerciales, consultorios y oficinas. Se instala en pared baja o en techo y distribuye el aire de forma uniforme.',
        highlights: [
            'Instalación en piso o techo',
            'Distribución de aire en 4 direcciones',
            'Ideal para locales de 45 a 60 m²',
        ],
        specs: [
            { label: 'Capacidad', value: '36.000 BTU (3 TR)' },
            { label: 'Tipo', value: 'Piso-techo' },
            { label: 'Voltaje', value: '220V / 60 Hz monofásico' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: '45 a 60 m²' },
            { label: 'Tiempo de entrega', value: '30 días aprox.' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-05-05T13:00:00.000Z',
    },
    {
        id: 'ac-midea-pt-60',
        slug: 'piso-techo-midea-60000-btu-trifasico',
        name: 'Piso-techo Midea 60.000 BTU Trifásico',
        category: 'aires-comerciales',
        brand: 'Midea',
        model: 'MUE-60CRN1',
        sku: 'MD-PT60-3F',
        price: 3600,
        stockMode: 'ON_ORDER',
        stock: 0,
        leadTimeDays: 45,
        btu: 60000,
        voltage: '208-230V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Alta capacidad para galpones, salones de eventos y oficinas de gran tamaño. Alimentación trifásica para un arranque estable.',
        highlights: [
            'Alimentación trifásica 208-230V',
            'Gran caudal de aire',
            'Panel de control con pantalla digital',
        ],
        specs: [
            { label: 'Capacidad', value: '60.000 BTU (5 TR)' },
            { label: 'Tipo', value: 'Piso-techo' },
            { label: 'Voltaje', value: '208-230V / 60 Hz trifásico' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: '80 a 100 m²' },
            { label: 'Tiempo de entrega', value: '45 días aprox.' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-05-20T13:00:00.000Z',
    },
    {
        id: 'ac-lg-cassette-36',
        slug: 'cassette-lg-inverter-36000-btu',
        name: 'Cassette LG Inverter 36.000 BTU',
        category: 'aires-comerciales',
        brand: 'LG',
        model: 'ATNQ36GNLE7',
        sku: 'LG-CS36-220',
        price: 2750,
        stockMode: 'ON_ORDER',
        stock: 0,
        leadTimeDays: 30,
        btu: 36000,
        voltage: '220V',
        isInverter: true,
        refrigerant: 'R410A',
        description:
            'Cassette de cuatro vías empotrado en techo falso: discreto, silencioso y con distribución de aire en 360°. Perfecto para oficinas y comercios.',
        highlights: [
            'Distribución de aire en 4 vías',
            'Bomba de condensado incorporada',
            'Compresor inverter de alta eficiencia',
        ],
        specs: [
            { label: 'Capacidad', value: '36.000 BTU (3 TR)' },
            { label: 'Tipo', value: 'Cassette 4 vías' },
            { label: 'Tecnología', value: 'Inverter' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Área recomendada', value: '45 a 60 m²' },
            { label: 'Tiempo de entrega', value: '30 días aprox.' },
        ],
        variants: [],
        tags: ['nuevo'],
        createdAt: '2026-08-28T13:00:00.000Z',
    },
    {
        id: 'part-capacitor-dual',
        slug: 'capacitor-dual-para-aire-acondicionado',
        name: 'Capacitor dual para aire acondicionado',
        category: 'repuestos',
        brand: 'Packard',
        model: 'Titan Pro',
        sku: 'PK-CAP-DUAL',
        price: 18,
        stockMode: 'STOCK',
        stock: 0,
        leadTimeDays: null,
        btu: null,
        voltage: '440V',
        isInverter: null,
        refrigerant: null,
        description:
            'Capacitor de marcha dual para compresor y ventilador de la unidad condensadora. Reemplazo directo en la mayoría de los equipos split.',
        highlights: [
            'Terminales para compresor, ventilador y común',
            'Carcasa de aluminio resistente',
            'Tolerancia de ±6 %',
        ],
        specs: [
            { label: 'Tipo', value: 'Capacitor de marcha dual' },
            { label: 'Voltaje', value: '370/440 VAC' },
            { label: 'Frecuencia', value: '50/60 Hz' },
        ],
        variants: [
            { id: 'part-capacitor-dual-35-5', label: '35+5 µF', priceDelta: 0, stock: 25 },
            { id: 'part-capacitor-dual-45-5', label: '45+5 µF', priceDelta: 4, stock: 18 },
        ],
        tags: ['bestseller'],
        createdAt: '2026-01-15T13:00:00.000Z',
    },
    {
        id: 'part-compressor-12k',
        slug: 'compresor-rotativo-12000-btu-r410a',
        name: 'Compresor rotativo 12.000 BTU R410A',
        category: 'repuestos',
        brand: 'GMCC',
        model: 'PA145G1C-4FTL',
        sku: 'GM-PA145-R410',
        price: 260,
        stockMode: 'STOCK',
        stock: 5,
        leadTimeDays: null,
        btu: 12000,
        voltage: '220V',
        isInverter: false,
        refrigerant: 'R410A',
        description:
            'Compresor rotativo de reemplazo para equipos split de 12.000 BTU con refrigerante R410A.',
        highlights: [
            'Compatible con la mayoría de los split de 12.000 BTU',
            'Incluye protector térmico',
        ],
        specs: [
            { label: 'Capacidad', value: '12.000 BTU' },
            { label: 'Tipo', value: 'Rotativo' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Refrigerante', value: 'R410A' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-02-01T13:00:00.000Z',
    },
    {
        id: 'part-board-universal',
        slug: 'tarjeta-electronica-universal-para-split',
        name: 'Tarjeta electrónica universal para split',
        category: 'repuestos',
        brand: 'QD',
        model: 'QD-U03C+',
        sku: 'QD-U03CP',
        price: 45,
        stockMode: 'STOCK',
        stock: 15,
        leadTimeDays: null,
        btu: null,
        voltage: '220V',
        isInverter: false,
        refrigerant: null,
        description:
            'Tarjeta de control universal con receptor y control remoto. Reemplaza la tarjeta original de equipos split convencionales de 9.000 a 24.000 BTU.',
        highlights: ['Incluye control remoto y receptor', 'Sensores de ambiente y tubería'],
        specs: [
            { label: 'Compatibilidad', value: 'Split convencional de 9.000 a 24.000 BTU' },
            { label: 'Voltaje', value: '220V' },
            { label: 'Incluye', value: 'Tarjeta, receptor, control y sensores' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-03-03T13:00:00.000Z',
    },
    {
        id: 'part-fan-motor',
        slug: 'motor-ventilador-condensadora-1-4-hp',
        name: 'Motor ventilador de condensadora 1/4 HP',
        category: 'repuestos',
        brand: 'Welling',
        model: 'YDK-60-6',
        sku: 'WL-YDK60',
        price: 65,
        stockMode: 'STOCK',
        stock: 8,
        leadTimeDays: null,
        btu: null,
        voltage: '220V',
        isInverter: null,
        refrigerant: null,
        description:
            'Motor para el ventilador de la unidad exterior de equipos split de 18.000 a 24.000 BTU.',
        highlights: ['Rodamientos sellados', 'Protección térmica integrada'],
        specs: [
            { label: 'Potencia', value: '1/4 HP' },
            { label: 'Voltaje', value: '220V / 60 Hz' },
            { label: 'Velocidad', value: '850 RPM' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-03-21T13:00:00.000Z',
    },
    {
        id: 'part-remote-universal',
        slug: 'control-remoto-universal-aire-acondicionado',
        name: 'Control remoto universal para aire acondicionado',
        category: 'repuestos',
        brand: 'Chunghop',
        model: 'K-1028E',
        sku: 'CH-K1028E',
        price: 12,
        stockMode: 'STOCK',
        stock: 50,
        leadTimeDays: null,
        btu: null,
        voltage: null,
        isInverter: null,
        refrigerant: null,
        description:
            'Control remoto universal compatible con más de 1.000 modelos de aires acondicionados. Configuración automática en segundos.',
        highlights: ['Búsqueda automática de código', 'Pantalla LCD con iluminación'],
        specs: [
            { label: 'Compatibilidad', value: 'Más de 1.000 modelos' },
            { label: 'Alimentación', value: '2 pilas AAA (no incluidas)' },
        ],
        variants: [],
        tags: ['bestseller'],
        createdAt: '2026-01-05T13:00:00.000Z',
    },
    {
        id: 'acc-copper-kit',
        slug: 'kit-tuberia-cobre-1-4-3-8',
        name: 'Kit de tubería de cobre 1/4" + 3/8"',
        category: 'accesorios',
        brand: 'Mueller',
        model: null,
        sku: 'MU-KIT-1438',
        price: 55,
        stockMode: 'STOCK',
        stock: 0,
        leadTimeDays: null,
        btu: null,
        voltage: null,
        isInverter: null,
        refrigerant: null,
        description:
            'Kit de tubería de cobre aislada para instalar equipos split de 9.000 a 12.000 BTU, con tuercas y cinta.',
        highlights: ['Cobre flexible con aislante térmico', 'Incluye tuercas flare y cinta'],
        specs: [
            { label: 'Diámetros', value: '1/4" (líquido) + 3/8" (succión)' },
            { label: 'Uso', value: 'Split de 9.000 a 12.000 BTU' },
        ],
        variants: [
            { id: 'acc-copper-kit-3m', label: '3 metros', priceDelta: 0, stock: 20 },
            { id: 'acc-copper-kit-5m', label: '5 metros', priceDelta: 30, stock: 12 },
        ],
        tags: [],
        createdAt: '2026-02-18T13:00:00.000Z',
    },
    {
        id: 'acc-gas-r410a',
        slug: 'gas-refrigerante-r410a-cilindro-11-kg',
        name: 'Gas refrigerante R410A, cilindro de 11,3 kg',
        category: 'accesorios',
        brand: 'Genetron',
        model: 'AZ-20',
        sku: 'GN-R410A-11',
        price: 160,
        compareAtPrice: 180,
        stockMode: 'STOCK',
        stock: 6,
        leadTimeDays: null,
        btu: null,
        voltage: null,
        isInverter: null,
        refrigerant: 'R410A',
        description:
            'Refrigerante R410A original en cilindro desechable, para carga y mantenimiento de equipos de aire acondicionado.',
        highlights: ['Pureza certificada', 'Válvula de carga estándar'],
        specs: [
            { label: 'Refrigerante', value: 'R410A' },
            { label: 'Contenido', value: '11,3 kg (25 lb)' },
        ],
        variants: [],
        tags: ['oferta'],
        createdAt: '2026-04-02T13:00:00.000Z',
    },
    {
        id: 'acc-wall-brackets',
        slug: 'base-soporte-de-pared-para-condensadora',
        name: 'Base soporte de pared para condensadora',
        category: 'accesorios',
        brand: 'Fast',
        model: 'BS-450',
        sku: 'FS-BS450',
        price: 28,
        stockMode: 'STOCK',
        stock: 25,
        leadTimeDays: null,
        btu: null,
        voltage: null,
        isInverter: null,
        refrigerant: null,
        description:
            'Par de bases de acero con pintura electrostática para colgar la unidad condensadora en la pared. Soporta equipos de hasta 24.000 BTU.',
        highlights: ['Acero reforzado anticorrosión', 'Incluye tornillería'],
        specs: [
            { label: 'Largo', value: '450 mm' },
            { label: 'Carga máxima', value: '100 kg' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-02-25T13:00:00.000Z',
    },
    {
        id: 'acc-drain-pump',
        slug: 'bomba-de-condensado-mini',
        name: 'Bomba de condensado mini',
        category: 'accesorios',
        brand: 'Aspen',
        model: 'Mini Orange',
        sku: 'AS-MINI-OR',
        price: 95,
        stockMode: 'ON_ORDER',
        stock: 0,
        leadTimeDays: 15,
        btu: null,
        voltage: '220V',
        isInverter: null,
        refrigerant: null,
        description:
            'Bomba de condensado silenciosa para cuando no hay pendiente natural para el drenaje. Se instala oculta junto a la unidad interior.',
        highlights: ['Funcionamiento silencioso', 'Para equipos de hasta 30.000 BTU'],
        specs: [
            { label: 'Caudal', value: '12 L/h' },
            { label: 'Voltaje', value: '220V' },
            { label: 'Tiempo de entrega', value: '15 días aprox.' },
        ],
        variants: [],
        tags: [],
        createdAt: '2026-06-18T13:00:00.000Z',
    },
]
