import type { MigrationInterface, QueryRunner } from 'typeorm'

/**
 * Converts every `timestamp` (without time zone) column to `timestamptz`.
 *
 * Why: node-postgres reads a `timestamp` value as *local time of the Node process*, and it writes
 * a JS Date as a local-time string with an offset that Postgres discards for `timestamp`. The DB
 * session runs in UTC, so the stored wall-clock values come from two different clocks:
 *
 * - Values produced by Postgres (`DEFAULT now()` on insert, `CURRENT_TIMESTAMP` that TypeORM uses
 *   for `@UpdateDateColumn` on update) are UTC wall-clock times.
 * - Values supplied by the app (only the seeded products' `created_at`) are wall-clock times in
 *   the Node process's local zone.
 *
 * Existing rows are converted to the instant they were meant to represent. Seeded products are the
 * only rows whose id is not a random UUID (see `newId()`), so they are the ones with app-supplied
 * `created_at`. The app zone is taken from the process running this migration (`TZ` or the system
 * zone), which must be the same machine/zone that ran the seed. On a UTC host both cases coincide.
 */
const UUID_PATTERN = '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

/** Columns whose existing values were always generated by Postgres (UTC wall clock). */
const DB_GENERATED_COLUMNS: ReadonlyArray<readonly [table: string, column: string]> = [
    ['users', 'created_at'],
    ['users', 'updated_at'],
    ['products', 'updated_at'],
    ['product_images', 'created_at'],
]

function appTimeZone(): string {
    return process.env.TZ?.trim() || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
}

async function assertKnownTimeZone(queryRunner: QueryRunner, zone: string): Promise<string> {
    const rows: unknown[] = await queryRunner.query(
        `SELECT 1 FROM pg_timezone_names WHERE name = $1`,
        [zone],
    )
    if (rows.length === 0) {
        throw new Error(`Unknown time zone "${zone}" for converting app-written timestamps.`)
    }
    // Safe to inline: it matched a row of pg_timezone_names, and quotes are escaped anyway.
    return `'${zone.replaceAll("'", "''")}'`
}

export class TimestampsWithTimeZone1790190086339 implements MigrationInterface {
    name = 'TimestampsWithTimeZone1790190086339'

    async up(queryRunner: QueryRunner): Promise<void> {
        const appZone = await assertKnownTimeZone(queryRunner, appTimeZone())

        for (const [table, column] of DB_GENERATED_COLUMNS) {
            await queryRunner.query(
                `ALTER TABLE "${table}" ALTER COLUMN "${column}" TYPE TIMESTAMP(3) WITH TIME ZONE
                 USING "${column}" AT TIME ZONE 'UTC'`,
            )
        }
        await queryRunner.query(
            `ALTER TABLE "products" ALTER COLUMN "created_at" TYPE TIMESTAMP(3) WITH TIME ZONE
             USING CASE
                 WHEN "id" ~ '${UUID_PATTERN}' THEN "created_at" AT TIME ZONE 'UTC'
                 ELSE "created_at" AT TIME ZONE ${appZone}
             END`,
        )
    }

    /** Restores the previous representation (UTC wall clock, app zone for seeded products). */
    async down(queryRunner: QueryRunner): Promise<void> {
        const appZone = await assertKnownTimeZone(queryRunner, appTimeZone())

        await queryRunner.query(
            `ALTER TABLE "products" ALTER COLUMN "created_at" TYPE TIMESTAMP(3)
             USING CASE
                 WHEN "id" ~ '${UUID_PATTERN}' THEN "created_at" AT TIME ZONE 'UTC'
                 ELSE "created_at" AT TIME ZONE ${appZone}
             END`,
        )
        for (const [table, column] of DB_GENERATED_COLUMNS) {
            await queryRunner.query(
                `ALTER TABLE "${table}" ALTER COLUMN "${column}" TYPE TIMESTAMP(3)
                 USING "${column}" AT TIME ZONE 'UTC'`,
            )
        }
    }
}
