import { feminine, masculine } from '../../common/validation/messages.js'

/** Spanish names of the product fields, used to build validation messages. */
export const FIELD = {
    slug: masculine('El slug'),
    name: masculine('El nombre'),
    category: feminine('La categoría'),
    price: masculine('El precio'),
    compareAtPrice: masculine('El precio anterior'),
    brand: feminine('La marca'),
    model: masculine('El modelo'),
    sku: masculine('El SKU'),
    stockMode: masculine('El modo de inventario'),
    leadTimeDays: masculine('El tiempo de entrega'),
    btu: feminine('La capacidad en BTU'),
    voltage: masculine('El voltaje'),
    isInverter: masculine('El indicador inverter'),
    refrigerant: masculine('El refrigerante'),
    specs: feminine('La ficha técnica'),
    specLabel: masculine('El nombre de la característica'),
    specValue: masculine('El valor de la característica'),
    description: feminine('La descripción'),
    highlights: feminine('La lista de destacados'),
    tags: feminine('La lista de etiquetas'),
    stock: masculine('El stock'),
    isActive: masculine('El estado activo'),
    variants: feminine('La lista de variantes'),
    variantLabel: feminine('La etiqueta de la variante'),
    variantPriceDelta: feminine('La diferencia de precio de la variante'),
    variantStock: masculine('El stock de la variante'),
    variantId: masculine('El identificador de la variante'),
    search: feminine('La búsqueda'),
    sort: masculine('El orden'),
    minPrice: masculine('El precio mínimo'),
    maxPrice: masculine('El precio máximo'),
    availability: feminine('La disponibilidad'),
    btuMin: feminine('La capacidad mínima en BTU'),
    btuMax: feminine('La capacidad máxima en BTU'),
    inverter: masculine('El filtro inverter'),
    page: feminine('La página'),
    pageSize: masculine('El tamaño de página'),
    limit: masculine('El límite'),
    productId: masculine('El producto'),
    availabilityItems: feminine('La lista de productos'),
} as const
